### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wenzezhang** [yutiansut/QUANTAXIS_Webkit#1]
when I want to use the command :"import  QUANTAXIS as QA"  I get the error:
 Import Error: No model named  queue

**Comment by yutiansut** [comment]
you are using python2? modify the [EventManger.py](https://github.com/yutiansut/QUANTAXIS/blob/0.3.8-dev-RC-ARP/QUANTAXIS/QASignal/EventManager.py)
```python
from queue import Queue, Empty
``` 
to 
```python
from Queue import Queue, Empty
``` 
and then 
```shell
python setup.py install
```

see the QUANTAXIS in https://github.com/yutiansut/QUANTAXIS
